/*
 * MDIO_config.h
 *
 *  Created on: Aug 2, 2023
 *      Author: Mahmoud
 *      Layer: MCAL
 *      Module: DIO
 *      Version: 1.00
 */

#ifndef MCAL_DIO_MDIO_CONFIG_H_
#define MCAL_DIO_MDIO_CONFIG_H_

/*set the port A pins as INPUT/OUTPUT*/
#define PORTA_PIN0_DIR	INPUT
#define PORTA_PIN1_DIR	INPUT
#define PORTA_PIN2_DIR	OUTPUT
#define PORTA_PIN3_DIR	OUTPUT
#define PORTA_PIN4_DIR	OUTPUT
#define PORTA_PIN5_DIR	OUTPUT
#define PORTA_PIN6_DIR	OUTPUT
#define PORTA_PIN7_DIR	OUTPUT

/*set the port A pins as LOW/HIGH*/
#define PORTA_PIN0_VALUE LOW
#define PORTA_PIN1_VALUE LOW
#define PORTA_PIN2_VALUE LOW
#define PORTA_PIN3_VALUE LOW
#define PORTA_PIN4_VALUE HIGH
#define PORTA_PIN5_VALUE HIGH
#define PORTA_PIN6_VALUE HIGH
#define PORTA_PIN7_VALUE HIGH

/*set the port B pins as INPUT/OUTPUT*/
#define PORTB_PIN0_DIR	INPUT
#define PORTB_PIN1_DIR	INPUT
#define PORTB_PIN2_DIR	INPUT
#define PORTB_PIN3_DIR	INPUT
#define PORTB_PIN4_DIR	OUTPUT
#define PORTB_PIN5_DIR	OUTPUT
#define PORTB_PIN6_DIR	OUTPUT
#define PORTB_PIN7_DIR	OUTPUT

/*set the port B pins as LOW/HIGH*/
#define PORTB_PIN0_VALUE LOW
#define PORTB_PIN1_VALUE LOW
#define PORTB_PIN2_VALUE LOW
#define PORTB_PIN3_VALUE LOW
#define PORTB_PIN4_VALUE LOW
#define PORTB_PIN5_VALUE LOW
#define PORTB_PIN6_VALUE LOW
#define PORTB_PIN7_VALUE LOW

/*set the port C pins as INPUT/OUTPUT*/
#define PORTC_PIN0_DIR	OUTPUT
#define PORTC_PIN1_DIR	OUTPUT
#define PORTC_PIN2_DIR	OUTPUT
#define PORTC_PIN3_DIR	OUTPUT
#define PORTC_PIN4_DIR	OUTPUT
#define PORTC_PIN5_DIR	OUTPUT
#define PORTC_PIN6_DIR	OUTPUT
#define PORTC_PIN7_DIR	OUTPUT

/*set the port C pins as LOW/HIGH*/
#define PORTC_PIN0_VALUE LOW
#define PORTC_PIN1_VALUE LOW
#define PORTC_PIN2_VALUE LOW
#define PORTC_PIN3_VALUE LOW
#define PORTC_PIN4_VALUE LOW
#define PORTC_PIN5_VALUE LOW
#define PORTC_PIN6_VALUE LOW
#define PORTC_PIN7_VALUE LOW

/*set the port D pins as INPUT/OUTPUT*/
#define PORTD_PIN0_DIR	OUTPUT
#define PORTD_PIN1_DIR	OUTPUT
#define PORTD_PIN2_DIR	OUTPUT
#define PORTD_PIN3_DIR	OUTPUT
#define PORTD_PIN4_DIR	OUTPUT
#define PORTD_PIN5_DIR	OUTPUT
#define PORTD_PIN6_DIR	OUTPUT
#define PORTD_PIN7_DIR	OUTPUT

/*set the port D pins as LOW/HIGH*/
#define PORTD_PIN0_VALUE LOW
#define PORTD_PIN1_VALUE LOW
#define PORTD_PIN2_VALUE LOW
#define PORTD_PIN3_VALUE LOW
#define PORTD_PIN4_VALUE LOW
#define PORTD_PIN5_VALUE LOW
#define PORTD_PIN6_VALUE LOW
#define PORTD_PIN7_VALUE LOW

#endif /* MCAL_DIO_MDIO_CONFIG_H_ */
