/*
 * M_ADC_config.h
 *
 *  Created on: Aug 9, 2023
 *      Author: Mahmoud
 */

#ifndef MCAL_ADC_M_ADC_CONFIG_H_
#define MCAL_ADC_M_ADC_CONFIG_H_

#define ADC_REFERENCE	AVCC

#define ADC_CHANNEL0	0

/*The ADC channel selection:
 *
0	SINGLE_ENDED	ADC0
1	SINGLE_ENDED	ADC1
2	SINGLE_ENDED	ADC2
3	SINGLE_ENDED	ADC3
4	SINGLE_ENDED	ADC4
5	SINGLE_ENDED	ADC5
6	SINGLE_ENDED	ADC6
7	SINGLE_ENDED	ADC7

8	POSITIVE_DIFFERENTIAL	ADC0	NEGATIVE_DIFFERENTIAL	ADC0	10X
9	POSITIVE_DIFFERENTIAL	ADC1	NEGATIVE_DIFFERENTIAL	ADC0	10X

10	POSITIVE_DIFFERENTIAL	ADC0	NEGATIVE_DIFFERENTIAL	ADC0	200X
11	POSITIVE_DIFFERENTIAL	ADC1	NEGATIVE_DIFFERENTIAL	ADC0	200X

12	POSITIVE_DIFFERENTIAL	ADC2	NEGATIVE_DIFFERENTIAL	ADC2	10X
13	POSITIVE_DIFFERENTIAL	ADC3	NEGATIVE_DIFFERENTIAL	ADC2	10X

14	POSITIVE_DIFFERENTIAL	ADC2	NEGATIVE_DIFFERENTIAL	ADC2	200X
15	POSITIVE_DIFFERENTIAL	ADC3	NEGATIVE_DIFFERENTIAL	ADC2	200X

16	POSITIVE_DIFFERENTIAL	ADC0	NEGATIVE_DIFFERENTIAL	ADC1	1X
17	POSITIVE_DIFFERENTIAL	ADC1	NEGATIVE_DIFFERENTIAL	ADC1	1X
18	POSITIVE_DIFFERENTIAL	ADC2	NEGATIVE_DIFFERENTIAL	ADC1	1X
19	POSITIVE_DIFFERENTIAL	ADC3	NEGATIVE_DIFFERENTIAL	ADC1	1X
20	POSITIVE_DIFFERENTIAL	ADC4	NEGATIVE_DIFFERENTIAL	ADC1	1X
21	POSITIVE_DIFFERENTIAL	ADC5	NEGATIVE_DIFFERENTIAL	ADC1	1X
22	POSITIVE_DIFFERENTIAL	ADC6	NEGATIVE_DIFFERENTIAL	ADC1	1X
23	POSITIVE_DIFFERENTIAL	ADC7	NEGATIVE_DIFFERENTIAL	ADC1	1X

24	POSITIVE_DIFFERENTIAL	ADC0	NEGATIVE_DIFFERENTIAL	ADC2	1X
25	POSITIVE_DIFFERENTIAL	ADC1	NEGATIVE_DIFFERENTIAL	ADC2	1X
26	POSITIVE_DIFFERENTIAL	ADC2	NEGATIVE_DIFFERENTIAL	ADC2	1X
27	POSITIVE_DIFFERENTIAL	ADC3	NEGATIVE_DIFFERENTIAL	ADC2	1X
28	POSITIVE_DIFFERENTIAL	ADC4	NEGATIVE_DIFFERENTIAL	ADC2	1X
29	POSITIVE_DIFFERENTIAL	ADC5	NEGATIVE_DIFFERENTIAL	ADC2	1X

30	SINGLE_ENDED	1.22V(VBG)
31	SINGLE_ENDED	0V(GND)

*/
#define ADC_u32IMEOUT	50000

/*Select Prescaler: DIV_2, DIV_4, DIV_8, DIV_16, DIV_32, DIV_64, DIV_128*/
#define PRESCALER	DIV_32

#endif /* MCAL_ADC_M_ADC_CONFIG_H_ */
